repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: end-of-file-fixer
        # exclude: '\.bat$'
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: validate-toml
